### ISSUE TITLE
UI Bugs in Filter Drawer

### ISSUE THREAD

**Issue by jaison080** [IEDCMEC/iedc-collab-frontend#235]
![image](https://github.com/IEDCMEC/iedc-collab/assets/93505829/7269ae3e-4b53-476e-98f6-0f21ce621348)

The Filter Chip Close Icon UI Can be Made better . You can refer to the one done in skills autocomplete of edit profile for reference.

**Comment by jaison080** [comment]
![image](https://github.com/IEDCMEC/iedc-collab/assets/93505829/35c37dfd-23fc-4ce2-abd6-188c50dc8e1e)


- Not Found Message in Developers can also be added for Projects if nothing matches.
- Instead of MUI Textfield for Start Typing... you can use normal input field and give Start Typing... as placeholder.
- What does this Search by Skills,Projects and Developers does , as of now there's some error and the whole site crashes. 😅😅
- As of now if you want yo ucan comment out the onCLick function of the above said.

**Comment by subru-37** [comment]
What does this Search by Skills,Projects and Developers does , as of now there's some error and the whole site crashes. 😅😅

- I do not know to be honest, I saw that design in the figma file earlier, but now it is missing, there is also no function called onClick the button so idk why it crashes, but no matter, there is no need for that filter now, (as there is no onClick function specified and it is not there in the figma file anymore)

**Comment by subru-37** [comment]
![image](https://github.com/IEDCMEC/iedc-collab/assets/93091455/b369f959-1c8d-4349-b695-12fc602fee44)
Is this fine?

**Comment by subru-37** [comment]
[pull request ](https://github.com/IEDCMEC/iedc-collab/pull/236)
- check this out
